//! Non-randomized, hand-picked, full-precision inputs and outputs, per
//! `docs/TESTING.md § Fixed regression cases`. Every assertion target here
//! was generated by running `sizing-core` itself (see
//! `examples/gen_cpmm_regression.rs`), never computed by hand — the value
//! matches `docs/whitepaper.md § 5.1`'s worked example to the precision
//! `rust_decimal` supports, but is taken from the actual program output,
//! per R11.

use rust_decimal_macros::dec;
use sizing_core::curves::{Cpmm, Pmm, StableSwap};
use sizing_core::{PricingCurve, SizingAlgorithm, SizingConstraints, SizingError};

#[test]
fn cpmm_regression_mispriced_pool() {
    let pool = Cpmm::new(dec!(1_200_000), dec!(800_000), dec!(0.997)).unwrap();
    let constraints = SizingConstraints {
        fixed_cost: dec!(0),
        max_size: None,
    };

    let result = pool.optimal_size(dec!(0.60), constraints).unwrap();

    // Generated by running the implementation (examples/gen_cpmm_regression.rs).
    assert_eq!(result.optimal_delta, dec!(63201.877941580268260688898696));
}

#[test]
fn cpmm_regression_no_arbitrage() {
    let pool = Cpmm::new(dec!(1_200_000), dec!(800_000), dec!(0.997)).unwrap();
    let constraints = SizingConstraints {
        fixed_cost: dec!(0),
        max_size: None,
    };

    let result = pool.optimal_size(dec!(0.6725), constraints);

    assert_eq!(result, Err(SizingError::NoArbitrageOpportunity));
}

#[test]
fn stableswap_regression_balanced_3pool() {
    let pool = StableSwap::new(
        vec![dec!(10_000_000), dec!(10_000_000), dec!(10_000_000)],
        dec!(100),
        dec!(0.997),
    )
    .unwrap();

    let (d, _iterations) = pool.solve_d().unwrap();

    // Balanced pool: D == S is the known analytic answer (whitepaper.md
    // § TESTING.md anchor regression). Assert within NEWTON_TOLERANCE.
    let expected = dec!(30_000_000);
    let relative_diff = (d - expected).abs() / expected;
    assert!(
        relative_diff < sizing_core::curves::stableswap::NEWTON_TOLERANCE,
        "D={d} not within NEWTON_TOLERANCE of {expected}"
    );
}

#[test]
fn stableswap_regression_imbalanced_3pool() {
    let pool = StableSwap::new(
        vec![dec!(15_000_000), dec!(8_000_000), dec!(9_500_000)],
        dec!(100),
        dec!(0.997),
    )
    .unwrap();

    let (d, iterations) = pool.solve_d().unwrap();

    assert!(iterations <= sizing_core::curves::stableswap::MAX_NEWTON_ITERATIONS);
    // Generated by running the implementation (examples/gen_stableswap_regression.rs).
    assert_eq!(d, dec!(32498614.222266699288032646314));
}

/// TESTING.md requires this case use "parameters taken from a worked
/// example in WooFi v2's own published documentation (not invented)."
/// After searching WooFi's official dev docs
/// (<https://learn.woo.org/woofi-docs/woofi-dev-docs/resources/the-math-behind-spmm>),
/// their audited GitHub repo (woonetwork/woofi_swap_smart_contracts), and
/// public audit reports, no complete numeric worked example was found —
/// only the symbolic formula (used elsewhere in this codebase, see
/// curves/pmm.rs) and scattered test-suite fragments missing the oracle
/// price/k setup needed to reproduce a full example. Per this project's stated decision-logging discipline
/// ("no mock data, no placeholder numbers... never invented"), I am not
/// fabricating a WooFi citation. This regression instead uses parameters
/// generated by actually running sizing-core itself
/// (examples/gen_pmm_regression.rs) — honest about its provenance rather
/// than mislabeled. DECISION MADE (R10): this test slot is intentionally
/// kept at its TESTING.md-specified name so the required test suite shape
/// stays intact; TESTING.md itself needs a note added acknowledging this
/// gap, and this test should be replaced if a genuine WooFi numeric
/// example is later located.
#[test]
fn pmm_regression_woofi_reference() {
    let pool = Pmm::new(
        dec!(1_000_000),
        dec!(2_000_000_000),
        dec!(2000),
        dec!(0.0000001),
    )
    .unwrap();

    let out = pool.quote(dec!(10_000)).unwrap();

    // Generated by running the implementation (examples/gen_pmm_regression.rs).
    assert_eq!(out, dec!(6666666.6666666666666666666667));
}
