from decimal import Decimal
from typing import Optional, List, Any

class PySizingConstraints:
    fixed_cost: Decimal
    max_size: Optional[Decimal]
    def __init__(self, fixed_cost: Decimal = Decimal(0), max_size: Optional[Decimal] = None) -> None: ...

class SizingResult:
    optimal_delta: Decimal
    expected_profit: Decimal
    guarantee_tier: str
    guarantee_tier_detail: Any
    iterations: Optional[int]

class PyCpmm:
    def __init__(self, x: Decimal, y: Decimal, fee_retention: Decimal) -> None: ...
    def quote(self, delta_in: Decimal) -> Decimal: ...
    def optimal_size(self, reference_price: Decimal, constraints: PySizingConstraints) -> SizingResult: ...

class PyStableSwap:
    def __init__(self, reserves: List[Decimal], amplification: Decimal, fee_retention: Decimal) -> None: ...
    def quote(self, delta_in: Decimal) -> Decimal: ...
    def optimal_size(self, reference_price: Decimal, constraints: PySizingConstraints) -> SizingResult: ...

class PyPmm:
    def __init__(self, base_reserve: Decimal, quote_reserve: Decimal, oracle_price: Decimal, k: Decimal) -> None: ...
    def quote(self, delta_in: Decimal) -> Decimal: ...
    def optimal_size(self, reference_price: Decimal, constraints: PySizingConstraints) -> SizingResult: ...

class PyConcentratedLiquidity:
    def __init__(self, liquidity: Decimal, sqrt_price_lower: Decimal, sqrt_price_upper: Decimal, sqrt_price_current: Decimal, fee_retention: Decimal) -> None: ...
    def quote(self, delta_in: Decimal) -> Decimal: ...
    def optimal_size(self, reference_price: Decimal, constraints: PySizingConstraints) -> SizingResult: ...

class PyBalancerWeightedPool:
    def __init__(self, reserves: List[Decimal], weights: List[Decimal], fee_retention: Decimal, input_index: int = 0, output_index: int = 1) -> None: ...
    def quote(self, delta_in: Decimal) -> Decimal: ...
    def optimal_size(self, reference_price: Decimal, constraints: PySizingConstraints) -> SizingResult: ...
